### ISSUE TITLE
curecoin-qt fails to build with boost 1.76.0, gcc 11.1.0

### ISSUE THREAD

**Issue by dark-saber** [cygnusxi/CurecoinSource#66]
curecoin-qt was building fine for me on Arch Linux until recently, and now it fails with following errors (with boost 1.76.0, gcc 11.1.0):
```
...
src/main.cpp: In function ‘bool CheckDiskSpace(uint64)’:
src/main.cpp:2545:34: error: reference to ‘filesystem’ is ambiguous
 2545 |     uint64 nFreeBytesAvailable = filesystem::space(GetDataDir()).available;
      |                                  ^~~~~~~~~~
...
src/main.cpp: At global scope:
src/main.cpp:2561:8: error: reference to ‘filesystem’ is ambiguous
 2561 | static filesystem::path BlockFilePath(unsigned int nFile)
      |        ^~~~~~~~~~
...
src/main.cpp: In function ‘FILE* OpenBlockFile(unsigned int, unsigned int, const char*)’:
src/main.cpp:2571:24: error: ‘BlockFilePath’ was not declared in this scope
 2571 |     FILE* file = fopen(BlockFilePath(nFile).string().c_str(), pszMode);
      |                        ^~~~~~~~~~~~~
...
make: *** [Makefile:2234: build/main.o] Error 1
==> ERROR: A failure occurred in build().
    Aborting...
```

**Comment by sjneph** [comment]
These errors should be resolved after pull request #67.

**Comment by cygnusxi** [comment]
merged #67
