### ISSUE TITLE
Cannot build on fresh install of Ubuntu 16.10 Desktop

### ISSUE THREAD

**Issue by Candunc** [cygnusxi/CurecoinSource#4]
I am getting the error:
```src/net.cpp:60:1: error: reference to ‘array’ is ambiguous
 array<int, THREAD_MAX> vnThreadsRunning;
 ^~~~~
In file included from src/net.h:9:0,
                 from src/main.h:10,
                 from src/db.h:8,
                 from src/net.cpp:7:
/usr/include/boost/array.hpp:60:11: note: candidates are: template<class T, long unsigned int N> class boost::array
     class array {
           ^~~~~
In file included from /usr/include/c++/6/tuple:39:0,
                 from /usr/include/c++/6/bits/stl_map.h:63,
                 from /usr/include/c++/6/map:61,
                 from src/util.h:17,
                 from src/bignum.h:12,
                 from src/main.h:8,
                 from src/db.h:8,
                 from src/net.cpp:7:
/usr/include/c++/6/array:90:12: note:                 template<class _Tp, long unsigned int _Nm> struct std::array
     struct array
            ^~~~~
Makefile:1192: recipe for target 'build/net.o' failed
make: *** [build/net.o] Error 1
````

I followed the guide in the README and have the latest versions of the recommended software:

```build-essential is already the newest version (12.1ubuntu2).
dh-make is already the newest version (2.201606).
libboost-dev is already the newest version (1.61.0.2).
libboost-program-options-dev is already the newest version (1.61.0.2).
libboost-system-dev is already the newest version (1.61.0.2).
libboost-thread-dev is already the newest version (1.61.0.2).
libdb5.3++-dev is already the newest version (5.3.28-12).
libminiupnpc-dev is already the newest version (1.9.20140610-2ubuntu2).
libqt4-dev is already the newest version (4:4.8.7+dfsg-7ubuntu1).
libssl-dev is already the newest version (1.0.2g-1ubuntu9).
qt4-qmake is already the newest version (4:4.8.7+dfsg-7ubuntu1).
libboost-filesystem-dev is already the newest version (1.61.0.2).```

**Comment by cygnusxi** [comment]
Thanks @Candunc merged your pull request and we can close this issue. Tested on 16.10 and 15.10
