### PR TITLE
OpenSSL 1.1.x fix and Boost 1.70+

### PR DESCRIPTION
**Pull request by Nuitari**
I've been having issues recompiling the wallet on recent OpenSSL, same issue as #21 , #28 
Includes the Boost 1.70+ fixes from #47 

This worked on Gentoo with OpenSSL 1.1.1b
I am able to connect to the network and get transactions.

I don't have the tooling in plate to test against OpenSSL 1.0

### CODE REVIEW

**Comment by Nuitari** [comment]
Some of the fixes come from the vertcoin-core project around bignum.h and script.h

**Comment by cygnusxi** [comment]
Hi @Nuitari, thanks for the help on this patch its much appreciated. If you want to join our discord https://discord.gg/jtztkFZ I'd like to send you some Curecoin for your help. Works great with new SSL and boost. 

I did test this with SSL 1.0.1 and ran into the following error. 

In file included from src/key.h:14:0,
                 from src/key.cpp:10:
src/util.h:245:22: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
     return strprintf("%"PRI64d, n);
                      ^
src/key.cpp: In function ‘int ECDSA_SIG_recover_key_GFp(EC_KEY*, ECDSA_SIG*, const unsigned char*, int, int, int)’:
src/key.cpp:82:5: error: ‘ECDSA_SIG_get0’ was not declared in this scope
     ECDSA_SIG_get0(ecsig, (const BIGNUM **)&s, 0);
     ^~~~~~~~~~~~~~
src/key.cpp:82:5: note: suggested alternative: ‘ECDSA_SIG_new’
     ECDSA_SIG_get0(ecsig, (const BIGNUM **)&s, 0);
     ^~~~~~~~~~~~~~
     ECDSA_SIG_new
src/key.cpp: In member function ‘bool CKey::SignCompact(uint256, std::vector<unsigned char>&)’:
src/key.cpp:317:5: error: ‘ECDSA_SIG_get0’ was not declared in this scope
     ECDSA_SIG_get0(sig, (const BIGNUM **)&r, (const BIGNUM **)&s);
     ^~~~~~~~~~~~~~
src/key.cpp:317:5: note: suggested alternative: ‘ECDSA_SIG_new’
     ECDSA_SIG_get0(sig, (const BIGNUM **)&r, (const BIGNUM **)&s);
     ^~~~~~~~~~~~~~
     ECDSA_SIG_new
src/key.cpp: In member function ‘bool CKey::SetCompactSignature(uint256, const std::vector<unsigned char>&)’:
src/key.cpp:364:5: error: ‘ECDSA_SIG_get0’ was not declared in this scope
     ECDSA_SIG_get0(sig, (const BIGNUM **)&r, (const BIGNUM **)&s);
     ^~~~~~~~~~~~~~
src/key.cpp:364:5: note: suggested alternative: ‘ECDSA_SIG_new’
     ECDSA_SIG_get0(sig, (const BIGNUM **)&r, (const BIGNUM **)&s);
     ^~~~~~~~~~~~~~
     ECDSA_SIG_new
Makefile:1472: recipe for target 'build/key.o' failed
make: *** [build/key.o] Error 1

**Comment by Nuitari** [comment]
Unfortunately I don't have openssl 1.0 anymore. I've pushed another change to have a compatibility  function for openssl 1.0, but I have no way to test it.
